### ISSUE TITLE
unbound MYSQL_ENV_MYSQL_ROOT_PASSWORD variable

### ISSUE THREAD

**Issue by zerr0s** [pschiffe/docker-pdns#10]
Hello,

I'm trying to spawn a powerdns dock using your image anad when the dock starts, it gives me:
```
pdns_1  | /docker-cmd.sh: line 10: MYSQL_ENV_MYSQL_ROOT_PASSWORD: unbound variable
powerdns_pdns_1 exited with code 1
```
I'm using mariadb:latest dock and th db dock is spawn like that:
version: "2"

```
services:
  db:
    image: mariadb:latest
    hostname: pdns-db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/pdns-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=myroot
      - MYSQL_DATABASE=pdns
      - MYSQL_USER=pdns
      - MYSQL_PASSWORD=mypdns
  pdns:
    image: pschiffe/pdns-mysql
    hostname: ns1
    domainname: domain.lan
    depends_on:
      - db
    links:
      - db:mysql
    ports:
      - 53:53
      - 53:53/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PDNS_master=yes
      - PDNS_api=yes
      - PDNS_webserver=yes
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_password=secret2
      - PDNS_version_string=anonymous
      - PDNS_default_ttl=120
      - PDNS_soa_minimum_ttl=600
      - PDNS_default_soa_name=ns1.domain.lan
      - PDNS_default_soa_mail=hostmaster@domain.lan
      - PDNS_allow_axfr_ips=127.0.0.1
```
Any idea ? thanks
