### ISSUE TITLE
`pdns-recursor` overrides address and port settings

### ISSUE THREAD

**Issue by troykelly** [pschiffe/docker-pdns#110]
The configuration below get's overridden with the default `0.0.0.0` `53` settings. Noting that the `local-address=0.0.0.0` and `local-port=53` settings are added to the config file even when those values are supplied by environment variables.

```yaml
  # Recursive Nameserver
  pdns_recursor:
    <<: *default-opts
    image: pschiffe/pdns-recursor:latest
    container_name: pdns_recursor
    network_mode: host
    restart: unless-stopped
    environment:
      - PDNS_api_key=${PDNS_RECURSOR_API_KEY}
      - PDNS_webserver=yes
      - PDNS_webserver_address=127.0.0.1
      - PDNS_webserver_password=${PDNS_RECURSOR_WEBSERVER_PASSWORD}
      - "PDNS_webserver-allow-from=::"
      - "PDNS_local-address=127.0.0.1:953"
      - "PDNS_local-port=953"
```

```text
[root@test-dns-001 /]# cat /etc/pdns-recursor/recursor.conf 
allow-from=0.0.0.0/0
api-key=password
daemon=no
local-address=127.0.0.1:953
local-port=953
local-address=0.0.0.0
local-port=53
setgid=pdns-recursor
setuid=pdns-recursor
webserver=yes
webserver-allow-from=::
webserver-address=127.0.0.1
webserver-password=password
```
