### ISSUE TITLE
REST API inconsistencies

### ISSUE THREAD

**Issue by asow25** [pschiffe/docker-pdns#114]
I'm using Kubernetes, all services seem to work fine.

Here's my problem, the API is configured, but from ```pdns-admin``` but I have no information about the server settings.

```
sh-5.2# curl -v http://master-api-pdns:8081/
* Trying 10.110.161.231:8081...
* Connected to master-api-pdns (10.110.161.231) port 8081 (#0)
> GET / HTTP/1.1
> Host: master-api-pdns:8081
> User-Agent: curl/7.87.0
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

And when I try to create a zone, I get an error :

[2023-07-01 19:35:52,443] [domain.py:281] ERROR - Cannot add zone devops.ci. ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

I think the connection via the api has failed, please help me!

**Comment by asow25** [comment]
# powerdns
```
apiVersion: v1
kind: Service
metadata:
  labels:
    .....
  namespace: dns
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app.kubernetes.io/name: pdns-master
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    .....
  name: master-pdns-secret
  namespace: dns
data:
  apikey: MTIzNDU2Nzg5MA==
  webserver: MTIzNDU2Nzg5MA==
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    .....
  name: pdns-master
  namespace: dns
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      .....
  template:
    metadata:
      labels:
        .....
    spec:
      nodeSelector:
        node-role.kubernetes.io/pdns-master: "true"
      containers:
      - image: pschiffe/pdns-mysql:alpine
        imagePullPolicy: IfNotPresent
        name: pdns-master
        env:
        - name: PDNS_gmysql_host
          value: "mariadb-pdns"
        - name: PDNS_gmysql_port
          value: "3306"
        - name: PDNS_gmysql_user
          valueFrom:
            secretKeyRef:
              name: mariadb-pdns-secret
              key: username
        - name: PDNS_gmysql_password
          valueFrom:
            secretKeyRef:
              name: mariadb-pdns-secret
              key: password
        - name: PDNS_gmysql_dbname
          value: "master_"
        - name: PDNS_version_string
          value: "anonymous"
        - name: PDNS_master
          value: "yes"
        - name: PDNS_api
          value: "yes"
        - name: PDNS_api_key
          valueFrom:
            secretKeyRef:
              name: master-pdns-secret
              key: apikey
        - name: PDNS_webserver
          value: "yes"
        - name: PDNS_webserver_address
          value: "0.0.0.0"
        - name: PDNS_webserver_allow_from
          value: "127.0.0.1/32 10.32.0.0/12"
        - name: PDNS_webserver_password
          valueFrom:
            secretKeyRef:
              name: master-pdns-secret
              key: webserver
        - name: PDNS_default_ttl
          value: "1500"
        - name: PDNS_default_soa_content
          value: "ns1.orange.ci dnsmaster.orange.ci"
        - name: PDNS_allow_axfr_ips
          value: "10.32.0.0/12"
        - name: PDNS_only_notify
          value: "10.32.0.0/12"
        - name: PDNS_dnsupdate
          value: "yes"
        - name: PDNS_allow_dnsupdate_from
          value: "10.0.0.1/32 127.0.0.1/32 10.32.0.0/12"
        ports:
        - name: dns-udp
          containerPort: 53
          protocol: UDP
          hostPort: 53
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
          hostPort: 53
        - name: powerdns-api
          containerPort: 8081
          protocol: TCP
```

# powerdns-admin
```
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
     .....
  name: pdns-admin-config
data:
  PDNS_ADMIN_SQLA_DB_HOST: "mariadb-pdns"
  PDNS_ADMIN_SQLA_DB_PORT: "3306"
  PDNS_ADMIN_SQLA_DB_USER: "root"
  PDNS_ADMIN_SQLA_DB_NAME: "pdnsadmin"
  PDNS_API_URL: "http://master-api-pdns:8081/"
  PDNS_VERSION: "4.7"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
     .....
  name: pdns-admin
spec:
   .....
  template:
     .....
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "pdns-admin-uwsgi"
      containers:
      - name: pdns-admin-static
        image: pschiffe/pdns-admin-static
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
      - name: pdns-admin-uwsgi
        image: pschiffe/pdns-admin-uwsgi
        imagePullPolicy: IfNotPresent
        env:
        - name: PDNS_ADMIN_SQLA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-pdns-secret
              key: password
        - name: PDNS_API_KEY
          valueFrom:
            secretKeyRef:
              name: master-pdns-secret
              key: apikey
        envFrom:
        - configMapRef:
            name: pdns-admin-config
        volumeMounts:
        - mountPath: /opt/powerdns-admin/upload/
          name: pdns-admin
      volumes:
      - name: pdns-admin
        persistentVolumeClaim:
          claimName: pdns-admin-pvc
```
