### ISSUE TITLE
Can't forward a zone

### ISSUE THREAD

**Issue by Isnubi** [pschiffe/docker-pdns#118]
Hello, 
I'm trying to configure a pdns authoritative server and a pdns-recursor along, like that:
![image](https://github.com/pschiffe/docker-pdns/assets/40593456/4a886419-530e-440e-892d-3e4f15a60a1b)

I'm facing the same issue than #98, that is the recursor don't forward the zone that I give to it.
The configuration line in the docker compose is well given to the container, here the recursor.conf file:
```
[root@1b26e68a614e /]# cat /etc/pdns-recursor/recursor.conf
aggressive-nsec-cache-size=0
allow-from=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
daemon=no
dnssec=off
forward-zones=test.local=10.0.3.251:5300
local-address=0.0.0.0
local-port=53
log-common-errors=yes
logging-facility=0
loglevel=6
quiet=no
setgid=pdns-recursor
setuid=pdns-recursor
```

For more context, when I try to dig a DNS entry on port 53, i got a SERVFAIL return. If I try to dig a external DNS (like google.com), it returns me the IP, via the external DNS i give to the host (here, 1.1.1.1).
But, when I do a dig, on the port of the pdns authoritative server (5300 here), it returns me the IP of my DNS entry.

I give you the three dig requests I do:
```
dig docker.test.local @10.0.3.251

; <<>> DiG 9.18.19-1~deb12u1-Debian <<>> docker.test.local@10.0.3.251
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 57434
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;docker.test.local. IN      A

;; Query time: 1508 msec
;; SERVER: 10.0.3.251#53(10.0.3.251) (UDP)
;; WHEN: Sat Oct 21 09:02:06 EDT 2023
;; MSG SIZE  rcvd: 46
```
```
dig google.com @10.0.3.251

; <<>> DiG 9.18.19-1~deb12u1-Debian <<>> google.com @10.0.3.251
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64545
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             300     IN      A       142.250.179.78

;; Query time: 64 msec
;; SERVER: 10.0.3.251#53(10.0.3.251) (UDP)
;; WHEN: Sat Oct 21 09:02:22 EDT 2023
;; MSG SIZE  rcvd: 55
```
```
dig docker.test.local @10.0.3.251 -p 5300

; <<>> DiG 9.18.19-1~deb12u1-Debian <<>> docker.test.local@10.0.3.251 -p 5300
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53457
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;docker.test.local. IN      A

;; ANSWER SECTION:
docker.test.local.      60      IN      A       10.0.3.1

;; Query time: 20 msec
;; SERVER: 10.0.3.251#5300(10.0.3.251) (UDP)
;; WHEN: Sat Oct 21 09:06:00 EDT 2023
;; MSG SIZE  rcvd: 62
```

Also, here's my docker-compose:
```
version: '3.8'
services:
  db:
    image: mariadb:latest
    container_name: db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=pdns
      - MYSQL_USER=pdns
      - MYSQL_PASSWORD=pdns
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
       - ./mysql:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 5

  web:
    image: powerdnsadmin/pda-legacy:latest
    container_name: pdns-admin
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql://pdns:pdns@10.0.3.251/pdns
      - GUNICORN_TIMEOUT=60
      - GUNICORN_WORKERS=2
      - GUNICORN_LOGLEVEL=DEBUG
    ports:
      - 8080:80
    logging:
      driver: json-file
      options:
        max-size: 50m
    depends_on:
      - db
      - pdns
    links:
      - db:mysql
      - pdns:pdns
    restart: unless-stopped

  pdns:
    image: pschiffe/pdns-mysql:latest
    container_name: pdns
    hostname: ns.test.local
    environment:
      # MYSQL BACKEND
      - PDNS_gmysql_host=10.0.3.251
      - PDNS_gmysql_port=3306
      - PDNS_gmysql_user=pdns
      - PDNS_gmysql_password=pdns
      - PDNS_gmysql_dbname=pdns
      # API
      - PDNS_api=yes
      - PDNS_api_key=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      - PDNSCONF_API_KEY=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      - PDNS_webserver=yes
      - PDNS_webserver-allow-from=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_password=bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
      # OPTIONS
      - PDNS_version_string=anonymous
      - PDNS_default_ttl=1500
      - PDNS_local_address=0.0.0.0
      - PDNS_local_port=5300
    ports:
      - 5300:5300
      - 5300:5300/udp
      - 8081:8081
    depends_on:
      - db
    links:
      - db:mysql
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro

  pdns-recursor:
    image: pschiffe/pdns-recursor:latest
    container_name: pdns-recursor
    environment:
      # FORWARD ZONE
      - PDNS_forward_zones=test.local=10.0.3.251:5300
      # OPTION
      - PDNS_local_address=0.0.0.0
      - PDNS_local_port=53
      - PDNS_allow_from=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      - PDNS_dnssec=off
      - PDNS_aggressive_nsec_cache_size=0
      # LOGGING
      - PDNS_logging_facility=0
      - PDNS_quiet=no
      - PDNS_loglevel=6
      - PDNS_log_common-errors=yes
    ports:
      - 53:53
      - 53:53/udp
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
```

**Comment by pschiffe** [comment]
Hello, I'm sorry for my late response. I've tried to reproduce this issue, but I cannot, it works for me. I've just pushed updated images, could you try with them? Also use `PDNS_loglevel: '7'` and `PDNS_trace: 'yes'` env vars for the recursor, it will log everything it's doing, the error should be visible there:
```
Dec 17 15:41:10 [0] docker.test.local: Using forwarder as NS
Dec 17 15:41:10 [0] docker.test.local: Cache consultations done, have 1 NS to contact
Dec 17 15:41:10 [0] docker.test.local: Domain has hardcoded nameserver
Dec 17 15:41:10 [0] docker.test.local: Nameservers: -172.5.0.20:53(0.00ms)
Dec 17 15:41:10 [0] docker.test.local: Resolved 'test.local' NS (empty) to: 172.5.0.20
Dec 17 15:41:10 [0] docker.test.local: Trying IP 172.5.0.20:53, asking 'docker.test.local|A'
Dec 17 15:41:10 [0] docker.test.local: Got 2 answers from (empty) (172.5.0.20), rcode=0 (No Error), aa=1, in 1ms
Dec 17 15:41:10 [0] docker.test.local: Accept answer 'docker.test.local|A|1.2.3.4' from 'test.local' nameservers? ttl=60, place=1 YES! - This answer was received from a server we forward to.
Dec 17 15:41:10 [0] docker.test.local: OPT answer '.' from 'test.local' nameservers
Dec 17 15:41:10 [0] docker.test.local: Determining status after receiving this packet
Dec 17 15:41:10 [0] docker.test.local: Answer is in: resolved to '1.2.3.4|A'
Dec 17 15:41:10 [0] docker.test.local: Status=got results, this level of recursion done
```

**Comment by Isnubi** [comment]
Hello,
Thanks for your answer !

I just retest the same setup with the updated images and the env parameters change for logging.

The resolution for external domain (google.com for example) works but not for the recursed domain (test.local here).
Here's what I have in the logs.

```
pdns-recursor  | Dec 17 16:33:35 [1] QM pschiffe.test.local: doResolve
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local: Wants NO DNSSEC processing, auth data required by query for A
pdns-recursor  | Dec 17 16:33:35 [1] QM pschiffe.test.local: Step0 Not cached
pdns-recursor  | Dec 17 16:33:35 [1] QM pschiffe.test.local: Step0 qname is in a forwarded domain test.local
pdns-recursor  | Dec 17 16:33:35 [1] QM pschiffe.test.local: Checking if we have NS in cache for 'pschiffe.test.local'
pdns-recursor  | Dec 17 16:33:35 [1] QM pschiffe.test.local: No valid/useful NS in cache for 'pschiffe.test.local'
pdns-recursor  | Dec 17 16:33:35 [1] QM pschiffe.test.local: Step2 New child pschiffe.test.local
pdns-recursor  | Dec 17 16:33:35 [1] QM pschiffe.test.local: Step3 Going to do final resolve
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local: Wants NO DNSSEC processing, auth data required by query for A
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local: No cache hit for 'pschiffe.test.local|A', trying to find an appropriate NS record
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local: Checking if we have NS in cache for 'pschiffe.test.local'
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local: No valid/useful NS in cache for 'pschiffe.test.local'
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local: Checking if we have NS in cache for 'test.local'
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local: No valid/useful NS in cache for 'test.local'
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local: Checking if we have NS in cache for 'local'
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local: No valid/useful NS in cache for 'local'
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local: Checking if we have NS in cache for '.'
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local: NS (with ip, or non-glue) in cache for '.' -> 'k.root-servers.net', within bailiwick: 1, in cache, ttl=86197
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local: NS (with ip, or non-glue) in cache for '.' -> 'g.root-servers.net', within bailiwick: 1, in cache, ttl=86197
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local: NS (with ip, or non-glue) in cache for '.' -> 'e.root-servers.net', within bailiwick: 1, in cache, ttl=86197
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local: NS (with ip, or non-glue) in cache for '.' -> 'c.root-servers.net', within bailiwick: 1, in cache, ttl=86197
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local: NS (with ip, or non-glue) in cache for '.' -> 'j.root-servers.net', within bailiwick: 1, in cache, ttl=86197
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local: NS (with ip, or non-glue) in cache for '.' -> 'a.root-servers.net', within bailiwick: 1, in cache, ttl=86197
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local: NS (with ip, or non-glue) in cache for '.' -> 'd.root-servers.net', within bailiwick: 1, in cache, ttl=86197
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local: NS (with ip, or non-glue) in cache for '.' -> 'm.root-servers.net', within bailiwick: 1, in cache, ttl=86197
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local: NS (with ip, or non-glue) in cache for '.' -> 'b.root-servers.net', within bailiwick: 1, in cache, ttl=86197
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local: NS (with ip, or non-glue) in cache for '.' -> 'f.root-servers.net', within bailiwick: 1, in cache, ttl=86197
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local: NS (with ip, or non-glue) in cache for '.' -> 'h.root-servers.net', within bailiwick: 1, in cache, ttl=86197
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local: NS (with ip, or non-glue) in cache for '.' -> 'i.root-servers.net', within bailiwick: 1, in cache, ttl=86197
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local: NS (with ip, or non-glue) in cache for '.' -> 'l.root-servers.net', within bailiwick: 1, in cache, ttl=86197
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local: We have NS in cache for '.' (flawedNSSet=0)
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local authOrForwDomain: test.local nsFromCacheDomain: . isPartof: 1
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local: Using forwarder as NS
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local: Cache consultations done, have 1 NS to contact
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local: Domain has hardcoded nameserver
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local: Nameservers: -10.0.3.251:5300(875.63ms)
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local: Resolved 'test.local' NS (empty) to: 10.0.3.251
pdns-recursor  | Dec 17 16:33:35 [1] pschiffe.test.local: Trying IP 10.0.3.251:5300, asking 'pschiffe.test.local|A'
pdns-recursor  | Dec 17 16:33:37 [1] pschiffe.test.local: Timeout resolving after 1502.43 ms
pdns-recursor  | Dec 17 16:33:37 [1] pschiffe.test.local: Failed to resolve via any of the 1 offered NS at level 'test.local'
pdns-recursor  | Dec 17 16:33:37 [1] pschiffe.test.local: Failed (res=-1)
pdns-recursor  | Dec 17 16:33:37 [1] QM pschiffe.test.local: Step3 Final resolve: Server Failure/0
pdns-recursor  | Dec 17 16:33:37 msg="Answer" subsystem="syncres" level="0" prio="Info" tid="1" ts="1702827217.349" additional="1" answer-is-variable="0" answers="0" dotout="0" ecs="" into-packetcache="1" maxdepth="0" mtid="1" netms="1502.435000" outqueries="1" proto="udp" qname="pschiffe.test.local" qtype="A" rcode="2" rd="1" remote="10.0.3.253:38658" tcpout="0" throttled="0" timeouts="1" totms="1507.161000" validationState="Indeterminate"
```

**Comment by pschiffe** [comment]
`Timeout resolving after 1502.43 ms` - the containers cannot talk to each other via that IP, as docker networking is doing NAT. Check your setup, use pdns container name in `PDNS_forward_zones=test.local=10.0.3.251:5300` instead of IP - that should work (like `PDNS_forward_zones=test.local=pdns:5300`) or use static IPs in the docker network, like it's done here: https://github.com/pschiffe/docker-pdns/blob/master/docker-compose.yml

**Comment by Isnubi** [comment]
> use pdns container name in PDNS_forward_zones=test.local=10.0.3.251:5300 instead of IP - that should work (like PDNS_forward_zones=test.local=pdns:5300)
This configuration don't work unfortunately.
```
pdns-recursor  | Dec 17 17:42:01 msg="Fatal error" error="Unable to convert presentation address 'pdns'" subsystem="config" level="0" prio="Critical" tid="0" ts="1702831321.337" exception="PDNSException"
```

I will try using docker network and go back to you!

**Comment by pschiffe** [comment]
Ah, I see, so it must be an IP. Other option could be to use network mode `host`, then the containers will be reachable on the `10.0.3.251`.

**Comment by Isnubi** [comment]
I manage to have something that works using docker network !
I don't use `host` network mode.

Here the `docker-compose.yml` I now have:
```yaml
version: '3.8'
services:
  pdns-recursor:
    image: pschiffe/pdns-recursor:latest
    container_name: pdns-recursor
    networks:
      - pdns-network
    environment:
      # FORWARD ZONE
      - PDNS_forward_zones=test.local=172.16.6.10:5300
      # OPTION
      - PDNS_local_address=0.0.0.0
      - PDNS_local_port=53
      - PDNS_allow_from=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      - PDNS_dnssec=off
      - PDNS_aggressive_nsec_cache_size=0
      # LOGGING
      - PDNS_logging_facility=0
      - PDNS_quiet=no
      - PDNS_loglevel=7
      - PDNS_trace=yes
      - PDNS_log_common-errors=yes
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 53:53
      - 53:53/udp
    restart: unless-stopped


  db:
    image: mariadb:latest
    container_name: db
    networks:
      - pdns-network
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=pdns
      - MYSQL_USER=pdns
      - MYSQL_PASSWORD=pdns
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
       - ./mysql:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 5

  web:
    image: powerdnsadmin/pda-legacy:latest
    container_name: pdns-admin
    networks:
      - pdns-network
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql://pdns:pdns@db/pdns
      - GUNICORN_TIMEOUT=60
      - GUNICORN_WORKERS=2
      - GUNICORN_LOGLEVEL=DEBUG
    ports:
      - 8080:80
    logging:
      driver: json-file
      options:
        max-size: 50m
    depends_on:
      - db
      - pdns
    links:
      - db:mysql
      - pdns:pdns
    restart: unless-stopped

  pdns:
    image: pschiffe/pdns-mysql:latest
    container_name: pdns
    networks:
      pdns-network:
        ipv4_address: 172.16.6.10
    environment:
      # MYSQL BACKEND
      - PDNS_gmysql_host=db
      - PDNS_gmysql_port=3306
      - PDNS_gmysql_user=pdns
      - PDNS_gmysql_password=pdns
      - PDNS_gmysql_dbname=pdns
      # API
      - PDNS_api=yes
      - PDNS_api_key=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      - PDNSCONF_API_KEY=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      - PDNS_webserver=yes
      - PDNS_webserver-allow-from=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_password=bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
      # OPTIONS
      - PDNS_version_string=anonymous
      - PDNS_default_ttl=1500
      - PDNS_local_address=0.0.0.0
      - PDNS_local_port=5300
    ports:
      - 5300:5300
      - 5300:5300/udp
      - 8081:8081
    depends_on:
      - db
    links:
      - db:mysql
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro

networks:
  pdns-network:
    ipam:
      config:
        - subnet: 172.16.6.0/24
```


I put the private docker subnet and, to be able to configure the forward zone in the recursor with the IP address of the AS, I define, statically, the IP address of the AS.
And so, the web admin UI and the recursor server is fetchable from the host IP address on the ports defined in the docker compose.

Thanks for your help !
