### ISSUE TITLE
Configuration problem

### ISSUE THREAD

**Issue by HerrSammyDE** [pschiffe/docker-pdns#124]
I tried to set up PowerDNS today, but I get `Received unsuccessful notification report for 'discord.com' from 100.0.0.2:53, error: Query Refused` at the master and unfortunately I don't know what to do.

I have censored my server data, which is why the master has `100.0.0.1` and my slave `100.0.0.2` as IP addresses.

Here are my Docker-Compose Configs:

**Master - docker-compose:**
```
version: '3'

services:
  pdns-master:
    image: pschiffe/pdns-mysql
    container_name: pdns-master
    hostname: ns1.domain.tld
    ports:
      - "100.0.0.1:53:53"
      - "100.0.0.1:53:53/udp"
      - "100.0.0.1:8081:8081"
      - "100.0.0.1:8081:8081/udp"
    environment:
      - PDNS_master=yes
      - PDNS_api=yes
      - PDNS_api_key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - PDNS_webserver=yes
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_allow_from=0.0.0.0/0
      - PDNS_webserver_password=XXXXXXXXX
      - PDNS_version_string=4.8.3
      - PDNS_default_ttl=1500
      - PDNS_allow_axfr_ips=100.0.0.2
      - PDNS_also_notify=100.0.0.2
      - PDNS_gmysql_host=XXXXXXXXX
      - PDNS_gmysql_port=3306
      - PDNS_gmysql_user=XXXXXXXXX
      - PDNS_gmysql_password=XXXXXXXXX
      - PDNS_gmysql_dbname=powerdnsmaster
      - PDNS_default_soa_content=ns1.domain.tld hostmaster.@ 0 10800 3600 604800 3600
      - PDNS_resolver=1.1.1.1,1.0.0.1,8.8.8.8,8.8.4.4,9.9.9.9,149.112.112.112,2001:4860:4860::8888,2001:4860:4860::8844
```

**Slave - docker-compose:**
```

version: '3'

services:
  pdns-slave:
    image: pschiffe/pdns-mysql
    container_name: pdns-slave
    hostname: ns2.domain.tld
    ports:
      - "100.0.0.2:53:53"
      - "100.0.0.2:53:53/udp"
      - "100.0.0.2:8081:8081"
      - "100.0.0.2:8081:8081/udp"
    environment:
      - PDNS_slave=yes
      - PDNS_webserver=yes
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_allow_from=0.0.0.0/0
      - PDNS_webserver_password=XXXXXXXXX
      - PDNS_version_string=4.8.3
      - PDNS_disable_axfr=no
      - PDNS_allow_notify_from=100.0.0.1
      - PDNS_allow_axfr_ips=100.0.0.1
      - SUPERMASTER_IPS=100.0.0.1
      - PDNS_gmysql_host=XXXXXXXXX
      - PDNS_gmysql_port=3306
      - PDNS_gmysql_user=XXXXXXXXX
      - PDNS_gmysql_password=XXXXXXXXX
      - PDNS_gmysql_dbname=powerdnsslave1
```

I hope you can help me. Thanks!
