### ISSUE TITLE
Healthcheck curl isn't effective and cause unhealthy container

### ISSUE THREAD

**Issue by leleobhz** [pschiffe/docker-pdns#125]
Currently pdns-admin uses curl to webservices to healthcheck, as in https://github.com/pschiffe/docker-pdns/blob/master/pdns-admin/Dockerfile#L72

This leads to unhealthy status (And tons of autoheal and daemonsets triggers) because curl redirects incorrectly:

```
[root@88f6e1fcf147 powerdns-admin]# curl -fsS http://127.0.0.1:8080 ; echo $?
0
[root@88f6e1fcf147 powerdns-admin]# curl -fsSL http://127.0.0.1:8080 ; echo $?
curl: (7) Failed to connect to 127.0.0.1 port 443: Connection refused
7
[root@88f6e1fcf147 powerdns-admin]#
```

But even if it's possible to remove `-L` option, I also suggest [bash internal tcp feature](https://tldp.org/LDP/abs/html/devref1.html#DEVTCP):

```
bash -c 'timeout 0.5 echo -n 2>/dev/null < /dev/tcp/127.0.0.1/8080 && (echo -n "http port open" ; exit 0) || (echo -n "http port closed" ; exit 1)'
```

I've tested this solution with docker-compose:

```
    healthcheck:
      test: bash -c 'timeout 0.5 echo -n 2>/dev/null < /dev/tcp/127.0.0.1/8080 && (echo -n "http port open" ; exit 0) || (echo -n "http port closed" ; exit 1)'
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 2m
```

And on runtime:

```
root@dns:/srv/docker/pdns# docker inspect pdns-admin | jq .[].State.Health
{
  "Status": "healthy",
  "FailingStreak": 0,
  "Log": [
    {
      "Start": "2024-01-23T18:47:38.620191149Z",
      "End": "2024-01-23T18:47:38.7482844Z",
      "ExitCode": 0,
      "Output": "http port open"
    }
  ]
}
```

Both solutions only check if door is open in practice, because current curl command line does not validate output (And even if tries to validade when we change to 8443, it leads to issues [1] if SNI is setup - also reported in [2])

That said, it's poissible to use bash solution (Can be used directly or via `/healtcheck.sh` script as example) instead curl?

[1]
```
[root@88f6e1fcf147 powerdns-admin]# curl -kfsS https://localhost:8443
curl: (35) error:0A000438:SSL routines::tlsv1 alert internal error
```

[2] https://caddy.community/t/openssl-3-1-4-errorssl-routines-tlsv1-alert-internal-error/21705
