### ISSUE TITLE
etc/pdns-recursor/recursor.conf

### ISSUE THREAD

**Issue by hpcmtint** [pschiffe/docker-pdns#131]
Hello Peter

```yaml

  pdns-recursor-mysql:
    image: pschiffe/pdns-recursor:${RECURSOR_TAG:-latest}
    networks:
      - pdns-mysql
    environment:
     - AUTH_ZONES=globe.local
     - FORWARD_ZONES=.=172.30.110.5,172.30.115.2    
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/data/recursor.conf:/etc/pdns-recursor/recursor.conf
    ulimits:
      nofile:
        soft: 5000
        hard: 5000
```
above is modified version of your recursor, i am unable to get it working and also    - /srv/data/recursor.conf:/etc/pdns-recursor/recursor.conf is being over written and if do 'ro' the container wont start.

forward-zones=.=172.30.110.5,172.30.115.2
