### ISSUE TITLE
High availability with Power DNS

### ISSUE THREAD

**Issue by skeita96** [pschiffe/docker-pdns#149]
Hello pschiffe,
I've seen your git repository, thanks for the work.
We want to set up a highly available powerDNS architecture for our domain that hosts our mail service.  The service is hosted on cloud A in case of unavailability and thanks to DRBD technology, the volume is migrated to cloud B. So we have our NS01 server on cloud A and the NS02 server on cloud B. So our wish is also that the mail services that were pointing to cloud A IPs, point to cloud B IPs.
In our research, LUA scripts could help us set up this architecture.
We are faced with the problem of loading the lua back-end into the PDNS containers.
I did a scratch installation on one of our servers where I was able to load the lua2 backend, but it was impossible for me to pass my script file from lua to pdns from the configurations.
Can you please give us some advice or guidelines to follow?

![Image](https://github.com/user-attachments/assets/e64e8f41-9158-4869-8885-316ee00865a3)

**Comment by pschiffe** [comment]
Hello @skeita96. I didn't really work with lua in pdns, maybe I won't be able to help you. What is this `lua2-dns-script` setting? I didn't find it in the documentation.

If you want to pass a file with lua script to container, you need to bind mount it from host to container, ie `docker run --volume <host-path>:<container-path>`. For details see https://docs.docker.com/engine/storage/bind-mounts/

**Comment by pschiffe** [comment]
There are basically 2 options. The HA on the pdns level with zone transfers between pdns primary and secondary - https://doc.powerdns.com/authoritative/modes-of-operation.html#primary-operation

Or the replication on the backend db side, passive HA with mysql/mariadb primary and its replica, or active-active ha with galera cluster, but that requires 3 servers minimum - https://doc.powerdns.com/authoritative/modes-of-operation.html#native-replication

**Comment by siegy22** [comment]
⚠ This is only a proof of concept, don't apply things like `PDNS_webserver_allow_from=0.0.0.0/0` in production. ⚠

I implemented this using PostgreSQL replication between two hosts to run a HA DNS service to the outside world.

**ns1.example.com**

```
services:
  postgres:
    image: postgres:16-alpine
    networks:
      pdns-pgsql:
        aliases:
          - db
          - pgsql
    ports:
      - "5432:5432"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - pgsql:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_PASSWORD=my-secret-pw
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      timeout: 10s
      retries: 5

  pdns-pgsql-master:
    image: pschiffe/pdns-pgsql:${PDNS_PGSQL_TAG:-latest}
    hostname: ns1.example.com
    networks:
      pdns-pgsql:
        aliases:
          - pdns
    extra_hosts:
      - 'ns1.example.com:<host1-ip>'
      - 'ns2.example.com:<host2-ip>'
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PDNS_gpgsql_password=my-secret-pw
      - PDNS_primary=yes
      - PDNS_api=yes
      - PDNS_api_key=secret
      - PDNS_webserver=yes
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_allow_from=0.0.0.0/0
      - PDNS_version_string=anonymous
      - PDNS_default_ttl=1500
    depends_on:
      - postgres
    ports:
      - "53:53/udp"
      - "8000:8000"

  pdns-admin-pgsql:
    image: pschiffe/pdns-admin
    networks:
      pdns-pgsql:
        aliases:
          - pdns-admin
    ports:
      - '7989:8080'
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PDNS_ADMIN_SQLA_DB_TYPE=postgres
      - PDNS_ADMIN_SQLA_DB_HOST=pgsql
      - PDNS_ADMIN_SQLA_DB_PORT=5432
      - PDNS_ADMIN_SQLA_DB_USER=postgres
      - PDNS_ADMIN_SQLA_DB_PASSWORD=my-secret-pw
      - PDNS_VERSION=4.9
      - PDNS_API_KEY=secret
    depends_on:
      - postgres
      - pdns-pgsql-master

networks:
  pdns-pgsql:

volumes:
  pgsql:
```
------

**ns2.example.com**

```
services:
  postgres:
    image: postgres:16-alpine
    networks:
      pdns-pgsql:
        aliases:
          - db
          - pgsql
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - pgsql:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_PASSWORD=my-secret-pw
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      timeout: 10s
      retries: 5
  pdns-pgsql-slave:
    image: pschiffe/pdns-pgsql:${PDNS_PGSQL_TAG:-latest}
    hostname: ns2.example.com
    networks:
      - pdns-pgsql
    extra_hosts:
      - 'ns1.example.com:<host1-ip>'
      - 'ns2.example.com:<host2-ip>'
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PDNS_gpgsql_password=my-secret-pw
      - PDNS_secondary=yes
      - PDNS_version_string=anonymous
      - PDNS_disable_axfr=yes
    depends_on:
      - postgres
    ports:
      - "53:53/udp"
      - "8000:8000"

networks:
  pdns-pgsql:

volumes:
  pgsql:
```

Enable replication on the primary host:

```
[user@host1 ~]$ docker compose exec -it postgres psql -U postgres -c "ALTER SYSTEM SET wal_level = replica;"
[user@host1 ~]$ docker compose exec -it postgres psql -U postgres -c "ALTER SYSTEM SET max_wal_senders = 5;"
[user@host1 ~]$ docker compose exec -it postgres psql -U postgres -c "ALTER SYSTEM SET hot_standby = on;"
[user@host1 ~]$ docker compose exec -it postgres psql -U postgres -c "ALTER SYSTEM SET listen_addresses = '*';"
```

Inital sync from secondary:
```
[user@host1 ~]$ docker compose run --rm postgres bash -c "pg_basebackup -h <host1-ip> -D /var/lib/postgresql/
data -U postgres -P -R --wal-method=stream"
[user@host1 ~]$ docker compose up -d
```

This will allow you to create "native" zones in PowerDNS. PostgreSQL will replicate everything and the secondary will serve the DNS requests.
