### ISSUE TITLE
Unknown server host 'mysql' (-2), PDNS_gmysql_host not working for k8s

### ISSUE THREAD

**Issue by SpiderUnderUrBed** [pschiffe/docker-pdns#151]
https://pastebin.com/ST0UTNh2
^ this is my configuration file, I get this error when i try to run it:
```
spiderunderurbed@raspberrypi:~/k8s $ kubectl logs pdns-mysql-master-97797b74-5s9j5
ERROR 2005 (HY000): Unknown server host 'mysql' (-2)
MySQL is unavailable - sleeping
ERROR 2005 (HY000): Unknown server host 'mysql' (-2)
MySQL is unavailable - sleeping
```
This issue is probably something stupid, but I have been stuck on it for quite awhile, I do not want to use the examples you have on a Kubernetes because I want a minimal setup among other things ill add, I am using k3s and also both the admin, and mysql pod seems to be running fine (minus the errors on my mysql thing), so nothing else is influencing it:
```
pdns-admin-mysql-6d9fcd6b89-gqjs2          1/1     Running       0          30s
pdns-mysql-master-97797b74-5s9j5           1/1     Running       0          73m
```

**Comment by SpiderUnderUrBed** [comment]
Wait I think i fixed it.

**Comment by SpiderUnderUrBed** [comment]
Nope, I dont know how to fix this.

**Comment by pschiffe** [comment]
Hello, service name is `mariadb`, but you should have that configured as well, based on your pastebin:
```
            - name: PDNS_gmysql_host
              value: "mariadb"
```

Make sure that this is also in the config file in the pod. `cat /etc/pdns/pdns.conf`

**Comment by SpiderUnderUrBed** [comment]
@pschiffe 
Sorry I was unavalible for awhile, here is my pdns.conf:
https://pastebin.com/X2wLVSnq
Updated pdns.yaml:
```
# PersistentVolume & PersistentVolumeClaim for MariaDB data
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/spiderunderurbed/k8s/pdns-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# PersistentVolume & PersistentVolumeClaim for zonesfiles configuration
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zonesfiles-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/spiderunderurbed/k8s/zonefiles
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zonesfiles-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Deployment for MariaDB (backend for PDNS)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:11-ubi
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "my-secret-pw"
            - name: TZ
              value: "UTC"
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-pvc
---
# Service for MariaDB
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      name: mysql
---
# Deployment for PDNS MySQL Master
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdns-mysql-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdns-mysql-master
  template:
    metadata:
      labels:
        app: pdns-mysql-master
    spec:
      containers:
        - name: pdns-mysql-master
          image: pschiffe/pdns-mysql:latest
          env:
            - name: PDNS_gmysql_host
              value: "mariadb"
              # Use the IP below if preferred:
              # value: "172.31.53.32"
            - name: PDNS_gmysql_port
              value: "3306"
            - name: PDNS_gmysql_user
              value: "pdns"
            - name: PDNS_gmysql_dbname
              value: "powerdnsadmin"
            - name: PDNS_gmysql_password
              value: "mypdns"   # Alternatively, you can reference an env variable here: ${MYSQL_PDNS_PASSWORD}
            - name: PDNS_master
              value: "yes"
            - name: PDNS_api
              value: "yes"
            - name: PDNS_api_key
              value: "secret"
            - name: PDNSCONF_API_KEY
              value: "secret"
            - name: PDNS_webserver
              value: "yes"
            - name: PDNS_webserver-allow-from
              value: "127.0.0.1,10.0.0.0/8,172.0.0.0/8,192.0.0.0/24,192.168.32.8/32,192.168.0.0/16"
            - name: PDNS_webserver_address
              value: "0.0.0.0"
            - name: PDNS_webserver_password
              value: "secret2"
            - name: PDNS_version_string
              value: "anonymous"
            - name: PDNS_default_ttl
              value: "1500"
            - name: PDNS_allow_notify_from
              value: "0.0.0.0"
            - name: PDNS_allow_axfr_ips
              value: "127.0.0.1"
            - name: PDNS_launch
              value: "bind,gmysql"
            - name: PDNS_bind-config
              value: "/bind.conf"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: zonesfile-storage
              mountPath: /zonesfiles.conf
              subPath: zonesfiles.conf
      volumes:
        - name: zonesfile-storage
          persistentVolumeClaim:
            claimName: zonesfiles-pvc
---
# Service for PDNS MySQL Master
apiVersion: v1
kind: Service
metadata:
  name: pdns-mysql-master
spec:
  selector:
    app: pdns-mysql-master
  ports:
    - protocol: TCP
      port: 53
      targetPort: 53
      name: dns-tcp
    - protocol: UDP
      port: 53
      targetPort: 53
      name: dns-udp
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: api
  type: LoadBalancer
---
# Deployment for PDNS Admin (Web UI)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdns-admin-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdns-admin-mysql
  template:
    metadata:
      labels:
        app: pdns-admin-mysql
    spec:
      containers:
        - name: pdns-admin-mysql
          image: pschiffe/pdns-admin
          env:
            - name: PDNS_gmysql_host
              value: "mariadb"
            - name: PDNS_ADMIN_SQLA_DB_PASSWORD
              value: "mypdns"
            - name: PDNS_VERSION
              value: "4.9"
            - name: PDNS_API_KEY
              value: "secret"
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: MYSQL_DATABASE
              value: "powerdnsadmin"
            - name: MYSQL_USER
              value: "pdns"
          ports:
            - containerPort: 8080
---
# Service for PDNS Admin
apiVersion: v1
kind: Service
metadata:
  name: pdns-admin-mysql
spec:
  selector:
    app: pdns-admin-mysql
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 8080
      name: web
---
# Ingress to direct HTTP traffic (nginx)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pdns-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: pdns.spidershomelab.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pdns-admin-mysql
                port:
                  number: 8989
---
# IngressRoute (Traefik)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pdns-route
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: (Host(`192.168.68.77`) && PathPrefix(`/pdns`)) || (Host(`192.168.1.22`) && PathPrefix(`/pdns`))
      kind: Rule
      middlewares:
        - name: general-middleware
      services:
        - name: pdns-admin-mysql
          port: 8989

```

Do you know what I did wrong in my configuration? for some reason the varibles are not passing into the container, could you maybe try to recreate it? Just the simple k8s config (I dont want the big one supplied)
