### ISSUE TITLE
Fix entrypoint script to ignore bad varibles

### ISSUE THREAD

**Issue by SpiderUnderUrBed** [pschiffe/docker-pdns#154]
When you start running this configuration, you are met with this:
```
Apr 27 01:28:32 msg="Fatal error" error="Trying to set unknown setting 'ADMIN-MYSQL-PORT'" subsystem="config" level="0" prio="Critical" tid="0" ts="1745717312.243" exception="PDNSException"
```
This is related to issue #47 
Unfortunately the fix mentioned there does not work for me, I assume Kubernetes passes environment variables to the pod, which is then applied to the config, if there was some way to ignore certain environment variables or better checking in place to stop setting such values inside the config file, for the recursor, or whatever other container is affected, it would fix this issue and improve usabillity.

```

# PersistentVolume & PersistentVolumeClaim for MariaDB data
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/spiderunderurbed/k8s/pdns-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# PersistentVolume & PersistentVolumeClaim for zonesfiles configuration
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zonesfiles-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/spiderunderurbed/k8s/zonefiles
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zonesfiles-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Deployment for MariaDB (backend for PDNS)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      nodeSelector:
        hostname: raspberrypi
      containers:
        - name: mariadb
          image: mariadb:11-ubi
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "my-secret-pw"
            - name: TZ
              value: "UTC"
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-pvc
---
# Service for MariaDB
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      name: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: powerdns-recursor
  labels:
    app: powerdns-recursor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: powerdns-recursor
  template:
    metadata:
      labels:
        app: powerdns-recursor
    spec:
      containers:
        - name: pdns-recursor
          image: pschiffe/pdns-recursor:latest  # <-- Replace with your actual image
          ports:
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
              protocol: TCP
          env:
            - name: PDNS_local_address
              value: "0.0.0.0"
            - name: PDNS_local_port
              value: "53"
            - name: PDNS_allow_from
              value: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
            - name: PDNS_dnssec
              value: "off"
            - name: PDNS_aggressive_nsec_cache_size
              value: "0"
            # Logging settings
            - name: PDNS_logging_facility
              value: "0"
            - name: PDNS_quiet
              value: "no"
            - name: PDNS_loglevel
              value: "7"
            - name: PDNS_trace
              value: "yes"
            - name: PDNS_log_common_errors
              value: "yes"
            # Forwarding zones: k8s internal & authoritative
            - name: PDNS_forward_zones
              value: |
                svc.cluster.local=10.43.0.10;
                cluster.local=10.43.0.10;
                in-addr.arpa=10.43.0.10;
                ip6.arpa=10.43.0.10;
                spidershomelab.xyz=pdns-mysql-master.default.svc.cluster.local;
                .=1.1.1.1
          ports:
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 53
              name: dns-udp
              protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: powerdns-recursor
spec:
  selector:
    app: powerdns-recursor
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
  type: ClusterIP
---
# Deployment for PDNS MySQL Master
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdns-mysql-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdns-mysql-master
  template:
    metadata:
      labels:
        app: pdns-mysql-master
    spec:
      nodeSelector:
        hostname: raspberrypi
      containers:
        - name: pdns-mysql-master
          image: pschiffe/pdns-mysql:latest
          command: ["/docker-entrypoint.sh", "/usr/sbin/pdns_server"]
          env:
            - name: PDNS_gmysql_host
              value: "mariadb"
            - name: PDNS_gmysql_port
              value: "3306"
            - name: PDNS_gmysql_user
              value: "pdns"
            - name: PDNS_gmysql_dbname
              value: "powerdnsadmin"
            - name: PDNS_gmysql_password
              value: "mypdns"
            - name: PDNS_master
              value: "yes"
            - name: PDNS_api
              value: "yes"
            - name: PDNS_api_key
              value: "secret"
            - name: PDNS_webserver
              value: "yes"
            - name: PDNS_webserver-allow-from
              value: "127.0.0.1,10.0.0.0/8,172.0.0.0/8,192.0.0.0/24,192.168.32.8/32,192.168.0.0/16"
            - name: PDNS_webserver_address
              value: "0.0.0.0"
            - name: PDNS_webserver_password
              value: "secret2"
            - name: PDNS_version_string
              value: "anonymous"
            - name: PDNS_default_ttl
              value: "1500"
            - name: PDNS_allow_notify_from
              value: "0.0.0.0"
            - name: PDNS_allow_axfr_ips
              value: "127.0.0.1"
            - name: PDNS_launch
              value: "bind,gmysql"
            - name: PDNS_bind-config
              value: "/bind.conf"
            # Point authoritative server at the recursor for recursion
            - name: PDNS_resolver
              value: "powerdns-recursor.default.svc.cluster.local"
            #- name: PDNS_recursor
            #  value: "pdns-recursor.default.svc.cluster.local"
          ports:
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 8081
              name: api
          volumeMounts:
            - name: zonesfile-storage
              mountPath: /zonesfiles.conf
              subPath: zonesfiles.conf
      volumes:
        - name: zonesfile-storage
          persistentVolumeClaim:
            claimName: zonesfiles-pvc
---
# Service for PDNS MySQL Master
apiVersion: v1
kind: Service
metadata:
  name: pdns-mysql-master
spec:
  selector:
    app: pdns-mysql-master
  ports:
    - protocol: TCP
      port: 53
      targetPort: 53
      name: dns-tcp
    - protocol: UDP
      port: 53
      targetPort: 53
      name: dns-udp
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: api
  type: LoadBalancer
---
# Deployment for PDNS Admin (Web UI)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdns-admin-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdns-admin-mysql
  template:
    metadata:
      labels:
        app: pdns-admin-mysql
    spec:
      nodeSelector:
        hostname: raspberrypi
      containers:
        - name: pdns-admin-mysql
          image: pschiffe/pdns-admin
# ngoduykhanh/powerdns-admin:latest-arm64
          env:
            - name: PDNS_ADMIN_SQLA_DB_TYPE
              value: "mysql"
            - name: PDNS_ADMIN_SQLA_DB_HOST
              value: "mariadb"
            - name: PDNS_ADMIN_SQLA_DB_PORT
              value: "3306"
            - name: PDNS_ADMIN_SQLA_DB_USER
              value: "pdns"
            - name: PDNS_ADMIN_SQLA_DB_PASSWORD
              value: "mypdns"
            - name: PDNS_ADMIN_SQLA_DB_NAME
              value: "powerdnsadmin"
            # PDNS Server configuration
            - name: PDNS_API_URL
              value: "http://pdns-mysql-master:8081/"
            - name: PDNS_API_KEY
              value: "secret"
            - name: PDNS_VERSION
              value: "4.9"
          ports:
            - containerPort: 8080
              name: web
---
# Service for PDNS Admin
apiVersion: v1
kind: Service
metadata:
  name: pdns-admin-mysql
spec:
  selector:
    app: pdns-admin-mysql
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: web
---
# Ingress to direct HTTP traffic (nginx)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pdns-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: pdns.spidershomelab.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pdns-admin-mysql
                port:
                  number: 8080
---
# IngressRoute (Traefik)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pdns-route
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: (Host(192.168.68.77) && PathPrefix(/pdns)) || (Host(192.168.1.22) && PathPrefix(/pdns))
      kind: Rule
      middlewares:
        - name: general-middleware
      services:
        - name: pdns-admin-mysql
          port: 8080
```

**Comment by pschiffe** [comment]
I think the source of this issue in this config is the service `pdns-admin-mysql`. It should help to rename that service.

Alternatively, a better solution here is to just disable this k8s feature in the pod spec with `enableServiceLinks: false` [doc](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#containers)

The config file setup in the entrypoint is fairly simple, just [a loop](https://github.com/pschiffe/docker-pdns/blob/master/pdns-mysql/pdns.conf.tpl) over `PDNS_*` env vars. And there is a lot of [config options](https://doc.powerdns.com/authoritative/settings.html), so it's not that trivial to check which config is valid and maintaining that list between versions.

So, the best solution here I think is to set `enableServiceLinks: false` in the `pdns-mysql-master` deployment.

**Comment by SpiderUnderUrBed** [comment]
@pschiffe 
Thanks! That fixed the original issue, I do have one more question, unrelated to the original issue, but I do not know how to troubleshoot nor fix it:
```
May 02 10:41:27 PowerDNS Authoritative Server 4.9.2 (C) PowerDNS.COM BV
May 02 10:41:27 Using 64-bits mode. Built using gcc 14.2.1 20240912 (Red Hat 14.2.1-3) on Oct  1 2024 00:00:00 by mockbuild@localhost.
May 02 10:41:27 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
May 02 10:41:27 [webserver] Listening for HTTP requests on 0.0.0.0:8081
May 02 10:41:27 Polled security status of version 4.9.2 at startup, no known issues reported: OK
input in flex scanner failed
May 02 10:41:27 Our pdns instance exited with code 2, respawning
May 02 10:41:28 Guardian is launching an instance
May 02 10:41:29 Loading '/usr/lib64/pdns/libbindbackend.so'
May 02 10:41:29 Loading '/usr/lib64/pdns/libgmysqlbackend.so'
May 02 10:41:29 This is a guarded instance of pdns
May 02 10:41:29 UDP server bound to 0.0.0.0:53
May 02 10:41:29 UDP server bound to [::]:53
May 02 10:41:29 TCP server bound to 0.0.0.0:53
May 02 10:41:29 TCP server bound to [::]:53
May 02 10:41:29 PowerDNS Authoritative Server 4.9.2 (C) PowerDNS.COM BV
May 02 10:41:29 Using 64-bits mode. Built using gcc 14.2.1 20240912 (Red Hat 14.2.1-3) on Oct  1 2024 00:00:00 by mockbuild@localhost.
May 02 10:41:29 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
```
So it keeps on saying:
`input in flex scanner failed`

I do not anything relating to this issue, how it happens, how the debug, the best I can do is leave you with my configuration which i refined, and most parts of it are working, like resolver, admin panel, mysql, I just need help with pdns itself:
https://pastebin.com/qDHtqzRp

**Comment by pschiffe** [comment]
I think it's something with the configuration; check if the file `/zonesfiles.conf` is correctly mounted. Try without
```
            - name: PDNS_bind-config
              value: "/zonesfiles.conf"
```

Check the generated config file.

**Comment by SpiderUnderUrBed** [comment]
My mistake, it was not being mounted correctly. I assumed it was something else, incase anyone wants my full config, here it is, you will have to generate zonefiles.conf and rename the folder location:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-init
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS powerdns;
    CREATE USER IF NOT EXISTS 'pdnsadmin'@'%' IDENTIFIED BY 'my-secret-pw';
    CREATE USER IF NOT EXISTS 'pdns'@'%' IDENTIFIED BY 'mypdns';
    GRANT ALL PRIVILEGES ON powerdns.* TO 'pdnsadmin'@'%';
    GRANT ALL PRIVILEGES ON powerdns.* TO 'pdns'@'%';
    FLUSH PRIVILEGES;

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/spiderunderurbed/k8s/pdns-db
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - raspberrypi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zonesfiles-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/spiderunderurbed/k8s/zonefiles
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - raspberrypi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zonesfiles-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      nodeSelector:
        kubernetes.io/hostname: raspberrypi
      securityContext:
        fsGroup: 999
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-pvc
        - name: init-scripts
          configMap:
            name: mariadb-init
      containers:
        - name: mariadb
          image: mariadb:11.7.2
          securityContext:
            runAsUser: 999
            runAsGroup: 999
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "my-secret-pw"
            - name: MYSQL_DATABASE
              value: "powerdns"
            - name: MYSQL_USER
              value: "pdnsadmin"
            - name: MYSQL_PASSWORD
              value: "my-secret-pw"
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
          ports:
            - containerPort: 3306
          readinessProbe:
            exec:
              command:
                - mariadb-admin
                - ping
                - -uroot
                - -pmy-secret-pw
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: powerdns-master
  labels:
    app: powerdns-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: powerdns-master
  template:
    metadata:
      labels:
        app: powerdns-master
    spec:
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: raspberrypi
      enableServiceLinks: false
      containers:
        - name: master
          image: pschiffe/pdns-mysql:latest
          command: ["/docker-entrypoint.sh", "/usr/sbin/pdns_server"]
          env:
            - name: PDNS_gmysql_host
              value: "mariadb"
            - name: PDNS_gmysql_port
              value: "3306"
            - name: PDNS_gmysql_user
              value: "pdns"
            - name: PDNS_gmysql_dbname
              value: "powerdns"
            - name: PDNS_gmysql_password
              value: "mypdns"
            - name: PDNS_primary
              value: "yes"
            - name: PDNS_api
              value: "yes"
            - name: PDNS_api_key
              value: "secret"
            - name: PDNS_webserver
              value: "yes"
            - name: PDNS_webserver-allow-from
              value: "127.0.0.1,10.0.0.0/8,172.0.0.0/8,192.0.0.0/24,192.168.32.8/32,192.168.0.0/16"
            - name: PDNS_webserver_address
              value: "0.0.0.0"
            - name: PDNS_webserver_password
              value: "secret2"
            - name: PDNS_version_string
              value: "anonymous"
            - name: PDNS_default_ttl
              value: "1500"
            - name: PDNS_allow_notify_from
              value: "0.0.0.0"
            - name: PDNS_allow_axfr_ips
              value: "127.0.0.1"
            - name: PDNS_launch
              value: "bind,gmysql"
            - name: PDNS_bind-config
              value: "/zonefiles/zonefile.conf"
          volumeMounts:
            - name: zonesfiles
              mountPath: /zonefiles
          ports:
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 8081
              name: api
              protocol: TCP
      volumes:
        - name: zonesfiles
          persistentVolumeClaim:
            claimName: zonesfiles-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: powerdns-master
spec:
  selector:
    app: powerdns-master
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: api
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
---
# PowerDNS Admin
apiVersion: apps/v1
kind: Deployment
metadata:
  name: powerdns-admin
  labels:
    app: powerdns-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: powerdns-admin
  template:
    metadata:
      labels:
        app: powerdns-admin
    spec:
      nodeSelector:
        kubernetes.io/hostname: raspberrypi
      containers:
        - name: powerdns-admin
          image: pschiffe/pdns-admin
          env:
            - name: PDNS_ADMIN_SQLA_DB_HOST
              value: "mariadb"
            - name: PDNS_ADMIN_SQLA_DB_PORT
              value: "3306"
            - name: PDNS_ADMIN_SQLA_DB_USER
              value: "pdns"
            - name: PDNS_ADMIN_SQLA_DB_PASSWORD
              value: "mypdns"
            - name: PDNS_ADMIN_SQLA_DB_NAME
              value: "powerdns"
            - name: TZ
              value: "UTC"
          ports:
            - containerPort: 80
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: powerdns-admin
spec:
  selector:
    app: powerdns-admin
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

```
