### ISSUE TITLE
where is docker-compose file to tie this altogether?

### ISSUE THREAD

**Issue by encryptblockr** [pschiffe/docker-pdns#28]
would be great to have a docker-compose file to just spin this all up

in the documentation/readme you mentioned https://github.com/pschiffe/docker-pdns#example

where you referenced `--link pdns-master:pdns` but no where in there did you mention how to run the `pdns-master` container. 
why did you omit this critical and important piece of the whole thing?
without that nothing will work and the point of the documentation is defeated

again a docker-compose file will help solve 99% of issues people will have running this

**Comment by encryptblockr** [comment]
here is a docker-compose file am working on

```
version: '3.7'

services:
  pdns-mysql-admin:
    image: mysql/mysql-server:latest
    hostname: pdns-mysql-admin
    ports:
      - '3306:3306'
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=PaSsWoRd123
      - MYSQL_DATABASE=powerdns
      - MYSQL_USER=powerdns
      - MYSQL_PASSWORD=PaSsWoRd123
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    
  pdns-master:
    image: pschiffe/pdns-mysql
    hostname: pdns-master
    networks:
      - backend
    environment:
      - PDNS_master=yes
      - PDNS_api=yes
      - PDNS_api_key=secret
      - PDNS_webserver=yes
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_password=secret2
      - PDNS_version_string=anonymous
      - PDNS_default_ttl=1500
      - PDNS_soa_minimum_ttl=1200
      - PDNS_default_soa_name=ns1.example.com
      - PDNS_default_soa_mail=hostmaster.example.com
      - PDNS_allow_axfr_ips=127.0.0.1
      - PDNS_gmysql_password=PaSsWoRd123
      - PDNS_gmysql_user=powerdns
    links:
      - pdns-mysql-admin:mysql
    depends_on:
      - pdns-mysql-admin

  pdns-admin-uwsgi:
    image: pschiffe/pdns-admin-uwsgi:ngoduykhanh
    hostname: pdns-admin-uwsgi
    networks:
      - backend
    environment:
      - PDNS_ADMIN_SQLA_DB_HOST=pdns-mysql-admin
      - PDNS_ADMIN_SQLA_DB_PORT=3306
      - PDNS_ADMIN_SQLA_DB_USER=powerdns
      - PDNS_ADMIN_SQLA_DB_PASSWORD=PaSsWoRd123
      - PDNS_ADMIN_SQLA_DB_NAME=powerdns
      - PDNS_API_URL="http://pdns:8081/"
      - PDNS_API_KEY="secret"
    links:
      - pdns-master:pdns
      - pdns-mysql-admin:mysql
    depends_on:
      - pdns-mysql-admin
      - pdns-master

  pdns-admin-web:
    image: pschiffe/pdns-admin-static:ngoduykhanh
    networks:
      - backend
      - frontend
    ports:
      - '8090:80'
    links:
      - pdns-admin-uwsgi
    depends_on:
      - pdns-admin-uwsgi

networks:
  backend:
    name: backend
  frontend:
    name: frontend
```


so when this issue https://github.com/pschiffe/docker-pdns/issues/29 gets fixed i will update so others can use
