### ISSUE TITLE
pdns-admin-uwsgi NameError: name 'pdns' is not defined

### ISSUE THREAD

**Issue by encryptblockr** [pschiffe/docker-pdns#29]
```
pdns-admin-uwsgi_1  | Traceback (most recent call last):
pdns-admin-uwsgi_1  |   File "/usr/local/bin/flask", line 10, in <module>
pdns-admin-uwsgi_1  |     sys.exit(main())
pdns-admin-uwsgi_1  |   File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 894, in main
pdns-admin-uwsgi_1  |     cli.main(args=args, prog_name=name)
pdns-admin-uwsgi_1  |   File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 557, in main
pdns-admin-uwsgi_1  |     return super(FlaskGroup, self).main(*args, **kwargs)
pdns-admin-uwsgi_1  |   File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 717, in main
pdns-admin-uwsgi_1  |     rv = self.invoke(ctx)
pdns-admin-uwsgi_1  |   File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 1137, in invoke
pdns-admin-uwsgi_1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
pdns-admin-uwsgi_1  |   File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 1137, in invoke
pdns-admin-uwsgi_1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
pdns-admin-uwsgi_1  |   File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 956, in invoke
pdns-admin-uwsgi_1  |     return ctx.invoke(self.callback, **ctx.params)
pdns-admin-uwsgi_1  |   File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 555, in invoke
pdns-admin-uwsgi_1  |     return callback(*args, **kwargs)
pdns-admin-uwsgi_1  |   File "/usr/local/lib64/python3.7/site-packages/click/decorators.py", line 17, in new_func
pdns-admin-uwsgi_1  |     return f(get_current_context(), *args, **kwargs)
pdns-admin-uwsgi_1  |   File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 411, in decorator
pdns-admin-uwsgi_1  |     with __ctx.ensure_object(ScriptInfo).load_app().app_context():
pdns-admin-uwsgi_1  |   File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 377, in load_app
pdns-admin-uwsgi_1  |     raise_if_not_found=False)
pdns-admin-uwsgi_1  |   File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 235, in locate_app
pdns-admin-uwsgi_1  |     __import__(module_name)
pdns-admin-uwsgi_1  |   File "/opt/powerdns-admin/app/__init__.py", line 24, in <module>
pdns-admin-uwsgi_1  |     app.config.from_object('config')
pdns-admin-uwsgi_1  |   File "/usr/local/lib/python3.7/site-packages/flask/config.py", line 170, in from_object
pdns-admin-uwsgi_1  |     obj = import_string(obj)
pdns-admin-uwsgi_1  |   File "/usr/local/lib/python3.7/site-packages/werkzeug/utils.py", line 546, in import_string
pdns-admin-uwsgi_1  |     __import__(import_name)
pdns-admin-uwsgi_1  |   File "/opt/powerdns-admin/config.py", line 7, in <module>
pdns-admin-uwsgi_1  |     SQLA_DB_HOST = pdns-mysql-admin
pdns-admin-uwsgi_1  | NameError: name 'pdns' is not defined
```

keeps getting this error `NameError: name 'pdns' is not defined` not sure what is happening
i see it connects to the database fine but then it exits with that error

here is my docker-compose file

```
version: '3.7'

services:
  pdns-mysql-admin:
    image: mysql/mysql-server:latest
    hostname: pdns-mysql-admin
    ports:
      - '3306:3306'
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=PaSsWoRd123
      - MYSQL_DATABASE=powerdns
      - MYSQL_USER=powerdns
      - MYSQL_PASSWORD=PaSsWoRd123
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    
  pdns-master:
    image: pschiffe/pdns-mysql
    hostname: pdns-master
    networks:
      - backend
    environment:
      - PDNS_master=yes
      - PDNS_api=yes
      - PDNS_api_key=secret
      - PDNS_webserver=yes
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_password=secret2
      - PDNS_version_string=anonymous
      - PDNS_default_ttl=1500
      - PDNS_soa_minimum_ttl=1200
      - PDNS_default_soa_name=ns1.example.com
      - PDNS_default_soa_mail=hostmaster.example.com
      - PDNS_allow_axfr_ips=127.0.0.1
      - PDNS_gmysql_password=PaSsWoRd123
      - PDNS_gmysql_user=powerdns
    links:
      - pdns-mysql-admin:mysql
    depends_on:
      - pdns-mysql-admin

  pdns-admin-uwsgi:
    image: pschiffe/pdns-admin-uwsgi:ngoduykhanh
    hostname: pdns-admin-uwsgi
    networks:
      - backend
    environment:
      - PDNS_ADMIN_SQLA_DB_HOST=pdns-mysql-admin
      - PDNS_ADMIN_SQLA_DB_PORT=3306
      - PDNS_ADMIN_SQLA_DB_USER=powerdns
      - PDNS_ADMIN_SQLA_DB_PASSWORD=PaSsWoRd123
      - PDNS_ADMIN_SQLA_DB_NAME=powerdns
      - PDNS_API_URL="http://pdns:8081/"
      - PDNS_API_KEY="secret"
    links:
      - pdns-master:pdns
      - pdns-mysql-admin:mysql
    depends_on:
      - pdns-mysql-admin
      - pdns-master

  pdns-admin-web:
    image: pschiffe/pdns-admin-static:ngoduykhanh
    networks:
      - backend
      - frontend
    ports:
      - '8090:80'
    links:
      - pdns-admin-uwsgi
    depends_on:
      - pdns-admin-uwsgi

networks:
  backend:
    name: backend
  frontend:
    name: frontend
```
