### ISSUE TITLE
Fatal error: Trying to set unknown parameter 'ADMIN-PORT'

### ISSUE THREAD

**Issue by vipinjn24** [pschiffe/docker-pdns#47]
Hi,

I am unable to start PDNS in kubernetes.

below is the recurring error I am facing with alpine image.

```
Oct 31 18:41:01 Guardian is launching an instance
Oct 31 18:41:01 Loading '/usr/lib/pdns/pdns/libgmysqlbackend.so'
Oct 31 18:41:01 This is a guarded instance of pdns
Oct 31 18:41:01 Fatal error: Trying to set unknown parameter 'ADMIN-PORT'
Oct 31 18:41:02 Our pdns instance exited with code 1, respawning
```

Please let me know what is the issue with the deployment.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pdns
    type: dns
  name: pdns-deployment
  namespace: dns
spec:
  selector:
    matchLabels:
      app: pdns
      type: dns
  template:
    metadata:
      labels:
        app: pdns
        type: dns
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "pdns-admin-uwsgi"
      containers:
      - image: pschiffe/pdns-mysql:alpine
        imagePullPolicy: IfNotPresent
        name: pdns-master
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: PDNS_gmysql_host
          value: "mysql.db"
        - name: PDNS_gmysql_port
          value: "3306"
        - name: PDNS_gmysql_user
          valueFrom:
            secretKeyRef:
              name: pdns-secret
              key: mysqluser
        - name: PDNS_gmysql_password
          valueFrom:
            secretKeyRef:
              name: pdns-secret
              key: mysqlpass
        - name: PDNS_gmysql_dbname
          value: "power_dns_live"
        - name: PDNS_version_string
          value: "anonymous"
        - name: PDNS_master
          value: "yes"
        - name: PDNS_api
          value: "yes"
        - name: PDNS_api_key
          valueFrom:
            secretKeyRef:
              name: pdns-secret
              key: apikey
        - name: PDNS_webserver
          value: "yes"
        - name: PDNS_webserver_address
          value: "0.0.0.0"
        - name: PDNS_webserver_allow_from
          value: "127.0.0.1/32 10.244.0.0/16 10.32.0.0/16"
        - name: PDNS_webserver_password
          valueFrom:
            secretKeyRef:
              name: pdns-secret
              key: webserver
        - name: PDNS_default_ttl
          value: "1500"
        - name: PDNS_soa_minimum_ttl
          value: "1200"
        - name: PDNS_default_soa_name
          value: "ns1.vjs.net.in"
        - name: PDNS_default_soa_mail
          value: "dnsmaster.vjs.net.in"
        - name: PDNS_allow_axfr_ips
          value: "10.0.0.2 10.0.0.3"
        - name: PDNS_only_notify
          value: "10.0.0.2 10.0.0.3"
        - name: PDNS_dnsupdate
          value: "yes"
        - name: PDNS_allow_dnsupdate_from
          value: "10.0.0.1/32 127.0.0.1/32 10.244.0.0/16 10.32.0.0/16"
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
      - name: pdns-admin-static
        image: pschiffe/pdns-admin-static:ngoduykhanh
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 300m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
      - name: pdns-admin-uwsgi
        image: pschiffe/pdns-admin-uwsgi:ngoduykhanh
        imagePullPolicy: IfNotPresent
        env:
        - name: PDNS_ADMIN_SQLA_DB_HOST
          value: "'mysql.db'"
        - name: PDNS_ADMIN_SQLA_DB_PORT
          value: "'3306'"
        - name: PDNS_ADMIN_SQLA_DB_USER
          valueFrom:
            secretKeyRef:
              name: pdns-secret
              key: quotedmysqluser
        - name: PDNS_ADMIN_SQLA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pdns-secret
              key: quotedmysqlpass
        - name: PDNS_ADMIN_SQLA_DB_NAME
          value: "'power_dns_admin_live'"
        - name: PDNS_API_URL
          value: "http://localhost:8081/"
        - name: PDNS_VERSION
          value: "4.2.1"
        - name: PDNS_API_KEY
          valueFrom:
            secretKeyRef:
              name: pdns-secret
              key: apikey
        volumeMounts:
          - name: uploads
            mountPath: /opt/powerdns-admin/upload/
        resources:
          limits:
            cpu: 300m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: pdns-admin-pvc
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
```

**Comment by vipinjn24** [comment]
Switched the yaml to single port but still the same error.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pdns
    type: dns
  name: pdns
  namespace: dns
spec:
  selector:
    matchLabels:
      app: pdns
      type: dns
  template:
    metadata:
      labels:
        app: pdns
        type: dns
    spec:
      containers:
      - image: pschiffe/pdns-mysql:alpine
        imagePullPolicy: IfNotPresent
        name: pdns-master
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: PDNS_gmysql_host
          value: "mysql.db"
        - name: PDNS_gmysql_port
          value: "3306"
        - name: PDNS_gmysql_user
          valueFrom:
            secretKeyRef:
              name: pdns-secret
              key: mysqluser
        - name: PDNS_gmysql_password
          valueFrom:
            secretKeyRef:
              name: pdns-secret
              key: mysqlpass
        - name: PDNS_gmysql_dbname
          value: "power_dns_live"
        - name: PDNS_version_string
          value: "anonymous"
        - name: PDNS_master
          value: "yes"
        - name: PDNS_api
          value: "yes"
        - name: PDNS_api_key
          valueFrom:
            secretKeyRef:
              name: pdns-secret
              key: apikey
        - name: PDNS_webserver
          value: "yes"
        - name: PDNS_webserver_address
          value: "0.0.0.0"
        - name: PDNS_webserver_allow_from
          value: "127.0.0.1/32 10.244.0.0/16 10.32.0.0/16"
        - name: PDNS_webserver_password
          valueFrom:
            secretKeyRef:
              name: pdns-secret
              key: webserver
        - name: PDNS_default_ttl
          value: "1500"
        - name: PDNS_soa_minimum_ttl
          value: "1200"
        - name: PDNS_default_soa_name
          value: "ns1.vjs.net.in"
        - name: PDNS_default_soa_mail
          value: "dnsmaster.vjs.net.in"
        - name: PDNS_allow_axfr_ips
          value: "10.0.0.2 10.0.0.3"
        - name: PDNS_only_notify
          value: "10.0.0.2 10.0.0.3"
        - name: PDNS_dnsupdate
          value: "yes"
        - name: PDNS_allow_dnsupdate_from
          value: "10.0.0.1/32 127.0.0.1/32 10.244.0.0/16 10.32.0.0/16"
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
```
